
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
     maximum-pool-size: 10
     minimum-idle: 5
     idle-timeout: 30000
     connection-timeout: 30000
     max-lifetime: 600000
     validation-timeout: 3000
  h2:
    console:
      enabled: true
  application:
    name: library-app		
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true				
resilience4j:
  retry:
    instances:
      openaiApiRetry:
        maxAttempts: 3  
        waitDuration: 5s  
     
          
  circuitbreaker:
    instances:
      openaiApiCircuitBreaker:
        registerHealthIndicator: true
        failureRateThreshold: 50 
        slidingWindowSize: 100 
        minimumNumberOfCalls: 5  
        waitDurationInOpenState: 10s 
        eventConsumerBufferSize: 10
openai:
  api:
    key: ${OPENAI_API_KEY}
    uri: "https://api.openai.com/v1/completions"
web:
 cors:
   allowed-origins: "http://localhost:3000"